import { requireAccessPermission } from "@/lib/access-control";
import { commercialListInput } from "@/lib/commercial-api";
import { encodeCommercialCursor } from "@/lib/commercial-api-support";
import { customerScopePredicate } from "@/lib/operations-access";
import { getPostgresPool } from "@/lib/postgres";
import { researchErrorResponse } from "@/lib/research-api";

export async function GET(request:Request){try{const {user,scope}=await requireAccessPermission(request,"ops.ledger.view");const {url,limit,cursor}=commercialListInput(request);const params:unknown[]=[];const where:string[]=[];const status=url.searchParams.get("status")?.trim();if(status){params.push(status);where.push(`o.status=$${params.length}`);}if(cursor){params.push(cursor.createdAt,cursor.id);where.push(`(o.created_at,o.id)<($${params.length-1}::timestamptz,$${params.length})`);}const scoped=customerScopePredicate(scope,{userId:user.id,organizationId:user.organizationId},"scope_order","o.user_id",params.length+1);params.push(...scoped.values);where.push(scoped.clause);params.push(limit+1);const pool=await getPostgresPool();const result=await pool.query(`SELECT o.id,o.order_no,o.user_id,o.plan_version_id,o.price_amount::text,o.price_currency,o.status,o.submitted_by_user_id,o.created_at,o.updated_at FROM commercial_membership_orders o LEFT JOIN (SELECT id AS customer_id,organization_id AS branch_id FROM users) scope_order ON scope_order.customer_id=o.user_id WHERE ${where.join(" AND ")} ORDER BY o.created_at DESC,o.id DESC LIMIT $${params.length}`,params);const rows=result.rows.slice(0,limit),last=rows.at(-1);return Response.json({orders:rows.map(r=>({id:r.id,orderNo:r.order_no,userId:r.user_id,planVersionId:r.plan_version_id,price:{amount:r.price_amount,currency:r.price_currency},status:r.status,submittedByUserId:r.submitted_by_user_id,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()})),nextCursor:result.rows.length>limit&&last?encodeCommercialCursor({createdAt:new Date(last.created_at).toISOString(),id:last.id}):null},{headers:{"cache-control":"no-store"}});}catch(error){return researchErrorResponse(error);}}

