import { requireAccessPermission } from "@/lib/access-control";
import { commercialJson,commercialListInput,requestId,requiredString,stringArray } from "@/lib/commercial-api";
import { encodeCommercialCursor } from "@/lib/commercial-api-support";
import { createMembershipOrder } from "@/lib/commercial-membership-service";
import { getPostgresPool } from "@/lib/postgres";
import { researchErrorResponse } from "@/lib/research-api";

export async function GET(request:Request){try{const {user}=await requireAccessPermission(request,"client.wallet.view");const {limit,cursor}=commercialListInput(request);const params:unknown[]=[user.id];let cursorSql="";if(cursor){params.push(cursor.createdAt,cursor.id);cursorSql=`AND (o.created_at,o.id)<($2::timestamptz,$3)`;}params.push(limit+1);const pool=await getPostgresPool();const result=await pool.query(`SELECT o.id,o.order_no,o.plan_version_id,o.price_amount::text,o.price_currency,o.status,o.created_at,o.updated_at FROM commercial_membership_orders o WHERE o.user_id=$1 ${cursorSql} ORDER BY o.created_at DESC,o.id DESC LIMIT $${params.length}`,params);const rows=result.rows.slice(0,limit);const last=rows.at(-1);return Response.json({orders:rows.map(row=>({id:row.id,orderNo:row.order_no,planVersionId:row.plan_version_id,price:{amount:row.price_amount,currency:row.price_currency},status:row.status,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()})),nextCursor:result.rows.length>limit&&last?encodeCommercialCursor({createdAt:new Date(last.created_at).toISOString(),id:last.id}):null},{headers:{"cache-control":"no-store"}});}catch(error){return researchErrorResponse(error);}}
export async function POST(request:Request){try{const {user}=await requireAccessPermission(request,"client.wallet.view");const body=await commercialJson(request);const pool=await getPostgresPool();const row=await createMembershipOrder(pool,{userId:user.id,planVersionId:requiredString(body,"planVersionId",100),acceptedDocumentVersionIds:stringArray(body,"acceptedDocumentVersionIds",3),idempotencyKey:requiredString(body,"idempotencyKey",128),requestId:requestId(request),ipAddress:request.headers.get("x-forwarded-for")?.split(",")[0]?.trim(),userAgent:request.headers.get("user-agent")??undefined});return Response.json({order:{id:row.id,orderNo:row.order_no,planVersionId:row.plan_version_id,price:{amount:String(row.price_amount),currency:row.price_currency},status:row.status,createdAt:new Date(row.created_at).toISOString()}},{status:201});}catch(error){return researchErrorResponse(error);}}
