"use client";

import { useEffect, useState } from "react";

export type AccountViewer={id:string;email:string;username?:string|null;nickname?:string|null;avatarUrl?:string|null;role:string};

const roleLabels:Record<string,{zh:string;en:string}>={hq_admin:{zh:"总公司超级管理员",en:"HQ Super Admin"},branch_admin:{zh:"分公司管理员",en:"Branch Admin"},manager:{zh:"经理",en:"Manager"},supervisor:{zh:"主管",en:"Supervisor"},employee:{zh:"员工",en:"Employee"},customer:{zh:"用户",en:"Member"}};

function useChinese(){const[v,setV]=useState(false);useEffect(()=>{const sync=()=>setV(document.documentElement.lang.startsWith("zh"));sync();const o=new MutationObserver(sync);o.observe(document.documentElement,{attributes:true,attributeFilter:["lang"]});return()=>o.disconnect()},[]);return v}

export default function AccountSettings({viewer,onUpdated,onLogout}:{viewer:AccountViewer;onUpdated:(viewer:AccountViewer)=>void;onLogout:()=>void}){
  const zh=useChinese();
  const [open,setOpen]=useState(false),[tab,setTab]=useState<"profile"|"password">("profile"),[message,setMessage]=useState("");
  const [profile,setProfile]=useState({username:viewer.username||"",nickname:viewer.nickname||"",avatarUrl:viewer.avatarUrl||""});
  const [password,setPassword]=useState({currentPassword:"",newPassword:"",confirmPassword:""});
  useEffect(()=>setProfile({username:viewer.username||"",nickname:viewer.nickname||"",avatarUrl:viewer.avatarUrl||""}),[viewer]);
  const displayName=viewer.nickname||viewer.username||viewer.email.split("@")[0];
  const role=roleLabels[viewer.role]||{zh:viewer.role,en:viewer.role};
  const saveProfile=async()=>{setMessage("");const response=await fetch("/api/account/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const payload=await response.json().catch(()=>({}));if(!response.ok){setMessage(payload.error||payload.message||(zh?"保存失败":"Save failed"));return}onUpdated(payload.user);setMessage(zh?"个人资料已保存":"Profile saved")};
  const savePassword=async()=>{setMessage("");if(password.newPassword!==password.confirmPassword){setMessage(zh?"两次输入的新密码不一致":"New passwords do not match");return}const response=await fetch("/api/account/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:password.currentPassword,newPassword:password.newPassword})});const payload=await response.json().catch(()=>({}));if(!response.ok){setMessage(payload.error||payload.message||(zh?"修改失败":"Update failed"));return}setPassword({currentPassword:"",newPassword:"",confirmPassword:""});setMessage(zh?"密码修改成功":"Password updated")};
  const uploadAvatar=(file?:File)=>{if(!file)return;if(file.size>300*1024){setMessage(zh?"头像请控制在 300KB 以内":"Avatar must be smaller than 300KB");return}const reader=new FileReader();reader.onload=()=>setProfile(current=>({...current,avatarUrl:String(reader.result||"")}));reader.readAsDataURL(file)};
  const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"}).catch(()=>undefined);setOpen(false);onLogout()};
  return <><button className="account-button" onClick={()=>setOpen(true)}>{profile.avatarUrl?<img src={profile.avatarUrl} alt=""/>:<span className="account-avatar">{displayName.slice(0,1).toUpperCase()}</span>}<span><b>{displayName}</b><small>{zh?role.zh:role.en}</small></span></button>{open&&<div className="dialog-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setOpen(false)}}><div className="dialog-card account-dialog" role="dialog" aria-modal="true"><button className="dialog-close" onClick={()=>setOpen(false)}>×</button><div className="account-heading"><span className="account-avatar large">{displayName.slice(0,1).toUpperCase()}</span><div><h3>{displayName}</h3><p>{viewer.email} · {zh?role.zh:role.en}</p></div></div><div className="account-tabs"><button className={tab==="profile"?"active":""} onClick={()=>{setTab("profile");setMessage("")}}>{zh?"个人资料":"Profile"}</button><button className={tab==="password"?"active":""} onClick={()=>{setTab("password");setMessage("")}}>{zh?"修改密码":"Password"}</button></div>{tab==="profile"?<div className="account-form"><label><span>{zh?"用户名":"Username"}</span><input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/></label><label><span>{zh?"昵称":"Nickname"}</span><input value={profile.nickname} onChange={e=>setProfile({...profile,nickname:e.target.value})}/></label><label><span>{zh?"头像地址":"Avatar URL"}</span><input value={profile.avatarUrl} onChange={e=>setProfile({...profile,avatarUrl:e.target.value})}/></label><label className="avatar-upload"><span>{zh?"或上传头像":"Or upload avatar"}</span><input type="file" accept="image/*" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label><button className="primary" onClick={saveProfile}>{zh?"保存资料":"Save profile"}</button></div>:<div className="account-form"><label><span>{zh?"当前密码":"Current password"}</span><input type="password" value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})}/></label><label><span>{zh?"新密码":"New password"}</span><input type="password" value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})}/></label><label><span>{zh?"确认新密码":"Confirm password"}</span><input type="password" value={password.confirmPassword} onChange={e=>setPassword({...password,confirmPassword:e.target.value})}/></label><button className="primary" onClick={savePassword}>{zh?"确认修改":"Update password"}</button></div>}{message&&<div className="account-message">{message}</div>}<button className="account-logout" onClick={logout}>{zh?"退出登录":"Sign out"}</button></div></div>}</>
}
