"use client";

import { useEffect, useState } from "react";

type Profile = { id:string; name:string; providerName:string; baseUrl:string; modelName:string; maskedApiKey:string; enabled:boolean };
type Binding = { role:string; profileId:string; modelName:string; configured:boolean };
const roleList = ["requirements","market_regime","proposal_a","proposal_b","adversarial_review","risk_review","report"];
const roleLabel:Record<string,string> = {requirements:"需求分析",market_regime:"市场状态",proposal_a:"提案 A",proposal_b:"提案 B",adversarial_review:"反方审查",risk_review:"风险审核",report:"报告生成"};
function apiMessage(payload:unknown,fallback:string){const error=payload&&typeof payload==="object"?(payload as {error?:unknown}).error:null;return error&&typeof error==="object"&&"message" in error?String((error as {message?:unknown}).message||fallback):fallback}

export function AgentRoleAdmin(){
  const[profiles,setProfiles]=useState<Profile[]>([]),[bindings,setBindings]=useState<Binding[]>([]),[selection,setSelection]=useState<Record<string,string>>({}),[editingId,setEditingId]=useState(""),[notice,setNotice]=useState("");
  const[form,setForm]=useState({name:"",providerName:"",baseUrl:"",modelName:"",apiKey:"",enabled:true});
  async function load(){const[pr,br]=await Promise.all([fetch("/api/admin/llm-profiles",{cache:"no-store"}),fetch("/api/admin/agent-role-bindings",{cache:"no-store"})]),p=await pr.json().catch(()=>null),b=await br.json().catch(()=>null);if(!pr.ok||!br.ok){setNotice(apiMessage(!pr.ok?p:b,"模型编排服务尚未配置"));return}setProfiles(p.profiles||[]);setBindings(b.bindings||[]);setSelection(Object.fromEntries((b.bindings||[]).map((item:Binding)=>[item.role,item.profileId])))}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
  function edit(profile?:Profile){setEditingId(profile?.id||"");setForm(profile?{name:profile.name,providerName:profile.providerName,baseUrl:profile.baseUrl,modelName:profile.modelName,apiKey:"",enabled:profile.enabled}:{name:"",providerName:"",baseUrl:"",modelName:"",apiKey:"",enabled:true})}
  async function saveProfile(){const response=await fetch(editingId?`/api/admin/llm-profiles/${editingId}`:"/api/admin/llm-profiles",{method:editingId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),payload=await response.json().catch(()=>null);setNotice(response.ok?"模型 Profile 已加密保存":apiMessage(payload,"保存失败"));if(response.ok){edit();await load()}}
  async function bind(role:string){const response=await fetch("/api/admin/agent-role-bindings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({role,profileId:selection[role],enabled:true})}),payload=await response.json().catch(()=>null);setNotice(response.ok?`${roleLabel[role]}已绑定`:apiMessage(payload,"绑定失败"));if(response.ok)await load()}
  async function test(role:string){setNotice(`${roleLabel[role]}连通测试中…`);const response=await fetch("/api/admin/agent-role-bindings/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role})}),payload=await response.json().catch(()=>null);setNotice(response.ok?`${roleLabel[role]}连接成功 · ${payload.modelName} · ${payload.latencyMs}ms`:apiMessage(payload,"连接失败"))}
  return <section className="agent-role-admin"><header><div><small>MODEL ORCHESTRATION</small><h3>多 Agent 模型 Profile 与角色绑定</h3><p>供应商地址和密钥仅管理员可见；客户只看到角色和模型名称。</p></div><button onClick={()=>edit()}>新增 Profile</button></header>{notice&&<p className="admin-notice">{notice}</p>}
    <div className="agent-profile-grid">{profiles.map(profile=><button key={profile.id} onClick={()=>edit(profile)}><b>{profile.name}</b><span>{profile.modelName}</span><small>{profile.providerName} · {profile.enabled?"启用":"停用"} · {profile.maskedApiKey}</small></button>)}</div>
    <div className="agent-profile-form"><label>配置名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>供应商（仅管理员可见）<input value={form.providerName} onChange={e=>setForm({...form,providerName:e.target.value})}/></label><label>HTTPS 接口地址<input value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})} placeholder="https://api.example.com/v1"/></label><label>模型名称<input value={form.modelName} onChange={e=>setForm({...form,modelName:e.target.value})}/></label><label>API Key<input type="password" value={form.apiKey} onChange={e=>setForm({...form,apiKey:e.target.value})} placeholder={editingId?"留空则保留原 Key":"首次配置必填"}/></label><label className="profile-enabled"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>启用此 Profile</label><button className="primary" onClick={()=>void saveProfile()}>{editingId?"更新 Profile":"保存 Profile"}</button></div>
    <div className="agent-binding-grid">{roleList.map(role=>{const binding=bindings.find(item=>item.role===role);return <article key={role}><div><b>{roleLabel[role]}</b><small>{binding?.configured?`${binding.modelName} · 已就绪`:"未配置，任务会暂停"}</small></div><select value={selection[role]||""} onChange={e=>setSelection({...selection,[role]:e.target.value})}><option value="">选择 Profile</option>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name} · {profile.modelName}</option>)}</select><button disabled={!selection[role]} onClick={()=>void bind(role)}>绑定</button><button disabled={!binding?.configured} onClick={()=>void test(role)}>测试</button></article>})}</div>
  </section>
}
