export type MarketCategory = "crypto" | "forex" | "metals" | "stocks";

export type MarketInstrument = { symbol: string; label: string; name: string; nameZh: string; category: MarketCategory; providerSymbol: string; aliases: string[] };

export const marketInstruments: MarketInstrument[] = [
  ["BTCUSD", "BTC/USD", "Bitcoin", "比特币", "crypto", "BTCUSDT", ["btc", "bitcoin", "比特币"]], ["ETHUSD", "ETH/USD", "Ethereum", "以太坊", "crypto", "ETHUSDT", ["eth", "ethereum", "以太坊"]], ["SOLUSD", "SOL/USD", "Solana", "索拉纳", "crypto", "SOLUSDT", ["sol", "solana", "索拉纳"]], ["XRPUSD", "XRP/USD", "XRP", "瑞波币", "crypto", "XRPUSDT", ["xrp", "瑞波"]], ["DOGEUSD", "DOGE/USD", "Dogecoin", "狗狗币", "crypto", "DOGEUSDT", ["doge", "dogecoin", "狗狗币"]], ["BNBUSD", "BNB/USD", "BNB", "币安币", "crypto", "BNBUSDT", ["bnb", "币安币"]], ["ADAUSD", "ADA/USD", "Cardano", "艾达币", "crypto", "ADAUSDT", ["ada", "cardano", "艾达币"]], ["LTCUSD", "LTC/USD", "Litecoin", "莱特币", "crypto", "LTCUSDT", ["ltc", "litecoin", "莱特币"]], ["LINKUSD", "LINK/USD", "Chainlink", "链链接", "crypto", "LINKUSDT", ["link", "chainlink", "链链接"]], ["AVAXUSD", "AVAX/USD", "Avalanche", "雪崩协议", "crypto", "AVAXUSDT", ["avax", "avalanche", "雪崩"]], ["TONUSD", "TON/USD", "Toncoin", "Ton 币", "crypto", "TONUSDT", ["ton", "toncoin"]], ["TRXUSD", "TRX/USD", "TRON", "波场", "crypto", "TRXUSDT", ["trx", "tron", "波场"]], ["DOTUSD", "DOT/USD", "Polkadot", "波卡", "crypto", "DOTUSDT", ["dot", "polkadot", "波卡"]], ["BCHUSD", "BCH/USD", "Bitcoin Cash", "比特币现金", "crypto", "BCHUSDT", ["bch", "bitcoin cash", "比特币现金"]], ["SUIUSD", "SUI/USD", "Sui", "Sui", "crypto", "SUIUSDT", ["sui"]], ["APTUSD", "APT/USD", "Aptos", "Aptos", "crypto", "APTUSDT", ["apt", "aptos"]], ["NEARUSD", "NEAR/USD", "NEAR Protocol", "NEAR 协议", "crypto", "NEARUSDT", ["near", "near protocol"]], ["ARBUSD", "ARB/USD", "Arbitrum", "Arbitrum", "crypto", "ARBUSDT", ["arb", "arbitrum"]], ["OPUSD", "OP/USD", "Optimism", "Optimism", "crypto", "OPUSDT", ["op", "optimism"]], ["UNIUSD", "UNI/USD", "Uniswap", "Uniswap", "crypto", "UNIUSDT", ["uni", "uniswap"]],
  ["EURUSD", "EUR/USD", "Euro / US Dollar", "欧元 / 美元", "forex", "EURUSD=X", ["eur", "euro", "欧元"]], ["GBPUSD", "GBP/USD", "British Pound / US Dollar", "英镑 / 美元", "forex", "GBPUSD=X", ["gbp", "pound", "英镑"]], ["USDJPY", "USD/JPY", "US Dollar / Japanese Yen", "美元 / 日元", "forex", "JPY=X", ["jpy", "yen", "日元"]], ["AUDUSD", "AUD/USD", "Australian Dollar / US Dollar", "澳元 / 美元", "forex", "AUDUSD=X", ["aud", "australian dollar", "澳元"]], ["USDCAD", "USD/CAD", "US Dollar / Canadian Dollar", "美元 / 加元", "forex", "CAD=X", ["cad", "canadian dollar", "加元"]], ["USDCHF", "USD/CHF", "US Dollar / Swiss Franc", "美元 / 瑞郎", "forex", "CHF=X", ["chf", "franc", "瑞郎"]], ["NZDUSD", "NZD/USD", "New Zealand Dollar / US Dollar", "新西兰元 / 美元", "forex", "NZDUSD=X", ["nzd", "new zealand dollar", "新西兰元"]], ["EURJPY", "EUR/JPY", "Euro / Japanese Yen", "欧元 / 日元", "forex", "EURJPY=X", ["eurjpy", "欧元日元"]], ["GBPJPY", "GBP/JPY", "British Pound / Japanese Yen", "英镑 / 日元", "forex", "GBPJPY=X", ["gbpjpy", "英镑日元"]],
  ["XAUUSD", "XAU/USD", "Gold", "黄金", "metals", "GC=F", ["xau", "gold", "黄金"]], ["XAGUSD", "XAG/USD", "Silver", "白银", "metals", "SI=F", ["xag", "silver", "白银"]],
  ["AAPL", "AAPL", "Apple", "苹果", "stocks", "AAPL", ["aapl", "apple", "苹果"]], ["TSLA", "TSLA", "Tesla", "特斯拉", "stocks", "TSLA", ["tsla", "tesla", "特斯拉"]], ["NVDA", "NVDA", "NVIDIA", "英伟达", "stocks", "NVDA", ["nvda", "nvidia", "英伟达"]], ["MSFT", "MSFT", "Microsoft", "微软", "stocks", "MSFT", ["msft", "microsoft", "微软"]], ["AMZN", "AMZN", "Amazon", "亚马逊", "stocks", "AMZN", ["amzn", "amazon", "亚马逊"]], ["META", "META", "Meta Platforms", "Meta", "stocks", "META", ["meta", "facebook"]], ["GOOGL", "GOOGL", "Alphabet", "谷歌", "stocks", "GOOGL", ["googl", "alphabet", "google", "谷歌"]], ["AMD", "AMD", "AMD", "超威半导体", "stocks", "AMD", ["amd", "超威半导体"]], ["NFLX", "NFLX", "Netflix", "奈飞", "stocks", "NFLX", ["nflx", "netflix", "奈飞"]],
].map(([symbol, label, name, nameZh, category, providerSymbol, aliases]) => ({ symbol, label, name, nameZh, category, providerSymbol, aliases } as MarketInstrument));

export async function GET() { return Response.json({ instruments: marketInstruments, updatedAt: new Date().toISOString(), source: "AgentNovas market catalog" }, { headers: { "cache-control": "no-store" } }); }
