// Generated by scripts/generate-api-route-inventory.mjs. Do not edit by hand.
export type ApiRouteInventoryEntry = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
  route: string;
  source: string;
};

export const API_ROUTE_INVENTORY = [
  {
    "method": "GET",
    "route": "/api/access/assignments",
    "source": "app/api/access/assignments/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/access/assignments",
    "source": "app/api/access/assignments/route.ts"
  },
  {
    "method": "DELETE",
    "route": "/api/access/assignments/:id",
    "source": "app/api/access/assignments/[id]/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/access/audit",
    "source": "app/api/access/audit/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/access/change-requests",
    "source": "app/api/access/change-requests/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/access/change-requests",
    "source": "app/api/access/change-requests/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/access/change-requests/:id/decisions",
    "source": "app/api/access/change-requests/[id]/decisions/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/access/me/effective",
    "source": "app/api/access/me/effective/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/access/permissions",
    "source": "app/api/access/permissions/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/access/role-templates",
    "source": "app/api/access/role-templates/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/access/role-templates",
    "source": "app/api/access/role-templates/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/access/roles",
    "source": "app/api/access/roles/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/access/roles",
    "source": "app/api/access/roles/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/access/roles/:id",
    "source": "app/api/access/roles/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/access/roles/:id/publish",
    "source": "app/api/access/roles/[id]/publish/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/account/llm-config",
    "source": "app/api/account/llm-config/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/account/llm-config",
    "source": "app/api/account/llm-config/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/account/llm-config/test",
    "source": "app/api/account/llm-config/test/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/account/password",
    "source": "app/api/account/password/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/account/profile",
    "source": "app/api/account/profile/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/account/profile",
    "source": "app/api/account/profile/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/admin/agent-role-bindings",
    "source": "app/api/admin/agent-role-bindings/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/admin/agent-role-bindings",
    "source": "app/api/admin/agent-role-bindings/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/admin/agent-role-bindings/test",
    "source": "app/api/admin/agent-role-bindings/test/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/admin/follow-policy",
    "source": "app/api/admin/follow-policy/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/admin/follow-policy",
    "source": "app/api/admin/follow-policy/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/admin/llm-config",
    "source": "app/api/admin/llm-config/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/admin/llm-config",
    "source": "app/api/admin/llm-config/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/admin/llm-config/test",
    "source": "app/api/admin/llm-config/test/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/admin/llm-profiles",
    "source": "app/api/admin/llm-profiles/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/admin/llm-profiles",
    "source": "app/api/admin/llm-profiles/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/admin/llm-profiles/:id",
    "source": "app/api/admin/llm-profiles/[id]/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/admin/runtime-explanation-bindings",
    "source": "app/api/admin/runtime-explanation-bindings/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/admin/runtime-explanation-bindings",
    "source": "app/api/admin/runtime-explanation-bindings/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/admin/runtime-explanation-bindings/test",
    "source": "app/api/admin/runtime-explanation-bindings/test/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/ai/conversations",
    "source": "app/api/ai/conversations/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/ai/conversations",
    "source": "app/api/ai/conversations/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/ai/conversations/:id",
    "source": "app/api/ai/conversations/[id]/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/ai/conversations/:id",
    "source": "app/api/ai/conversations/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/ai/conversations/:id/messages",
    "source": "app/api/ai/conversations/[id]/messages/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/ai/conversations/:id/messages/:messageId/strategy",
    "source": "app/api/ai/conversations/[id]/messages/[messageId]/strategy/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/approvals",
    "source": "app/api/approvals/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/approvals/:id/decision",
    "source": "app/api/approvals/[id]/decision/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/attributions/requests",
    "source": "app/api/attributions/requests/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/attributions/transfers",
    "source": "app/api/attributions/transfers/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/forgot-password",
    "source": "app/api/auth/forgot-password/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/login",
    "source": "app/api/auth/login/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/logout",
    "source": "app/api/auth/logout/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/auth/me",
    "source": "app/api/auth/me/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/mfa/verify",
    "source": "app/api/auth/mfa/verify/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/register",
    "source": "app/api/auth/register/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/reset-password",
    "source": "app/api/auth/reset-password/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/auth/verify-email",
    "source": "app/api/auth/verify-email/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/automation/demo-cycle",
    "source": "app/api/automation/demo-cycle/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/automation/platform-ai-cycle",
    "source": "app/api/automation/platform-ai-cycle/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/data-center",
    "source": "app/api/data-center/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/employee/tasks",
    "source": "app/api/employee/tasks/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/exchange-accounts",
    "source": "app/api/exchange-accounts/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/exchange-accounts",
    "source": "app/api/exchange-accounts/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/exchange-accounts/:id",
    "source": "app/api/exchange-accounts/[id]/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/exchange-accounts/:id/perpetual-instruments",
    "source": "app/api/exchange-accounts/[id]/perpetual-instruments/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/exchange-accounts/:id/routing",
    "source": "app/api/exchange-accounts/[id]/routing/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/finance/adjustments",
    "source": "app/api/finance/adjustments/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/finance/collections",
    "source": "app/api/finance/collections/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/finance/collections/:id/confirm-paid",
    "source": "app/api/finance/collections/[id]/confirm-paid/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/finance/collections/refresh",
    "source": "app/api/finance/collections/refresh/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/finance/payout-profiles",
    "source": "app/api/finance/payout-profiles/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/finance/payout-profiles",
    "source": "app/api/finance/payout-profiles/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/finance/settlements",
    "source": "app/api/finance/settlements/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/finance/settlements",
    "source": "app/api/finance/settlements/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/finance/settlements/:id/paid",
    "source": "app/api/finance/settlements/[id]/paid/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/health",
    "source": "app/api/health/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/integrations/catalog",
    "source": "app/api/integrations/catalog/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/integrations/payments/:provider/webhook",
    "source": "app/api/integrations/payments/[provider]/webhook/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/integrations/resend/webhook",
    "source": "app/api/integrations/resend/webhook/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/invitations",
    "source": "app/api/invitations/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/invitations",
    "source": "app/api/invitations/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/maintenance/email/status",
    "source": "app/api/maintenance/email/status/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/maintenance/email/test",
    "source": "app/api/maintenance/email/test/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/maintenance/payment-providers",
    "source": "app/api/maintenance/payment-providers/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/maintenance/payment-providers/:id/status",
    "source": "app/api/maintenance/payment-providers/[id]/status/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/maintenance/payment-providers/:id/test",
    "source": "app/api/maintenance/payment-providers/[id]/test/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/maintenance/payment-workers/health",
    "source": "app/api/maintenance/payment-workers/health/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/maintenance/platform-settings",
    "source": "app/api/maintenance/platform-settings/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/maintenance/platform-settings",
    "source": "app/api/maintenance/platform-settings/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/maintenance/trading/emergency-stop",
    "source": "app/api/maintenance/trading/emergency-stop/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/maintenance/trading/emergency-stop",
    "source": "app/api/maintenance/trading/emergency-stop/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/market/candles",
    "source": "app/api/market/candles/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/market/instruments",
    "source": "app/api/market/instruments/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/market/news",
    "source": "app/api/market/news/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/market/quote",
    "source": "app/api/market/quote/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/market/ticker",
    "source": "app/api/market/ticker/route.ts"
  },
  {
    "method": "DELETE",
    "route": "/api/market/watchlist",
    "source": "app/api/market/watchlist/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/market/watchlist",
    "source": "app/api/market/watchlist/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/market/watchlist",
    "source": "app/api/market/watchlist/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/notifications/channels",
    "source": "app/api/notifications/channels/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/notifications/channels",
    "source": "app/api/notifications/channels/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/notifications/channels",
    "source": "app/api/notifications/channels/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/notifications/inbox",
    "source": "app/api/notifications/inbox/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/notifications/inbox",
    "source": "app/api/notifications/inbox/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/notifications/preferences",
    "source": "app/api/notifications/preferences/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/notifications/preferences",
    "source": "app/api/notifications/preferences/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/operations/deposit-action-requests",
    "source": "app/api/operations/deposit-action-requests/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/operations/deposit-action-requests/:id/decisions",
    "source": "app/api/operations/deposit-action-requests/[id]/decisions/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/operations/deposits",
    "source": "app/api/operations/deposits/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/operations/deposits/:id",
    "source": "app/api/operations/deposits/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/operations/deposits/:id/action-requests",
    "source": "app/api/operations/deposits/[id]/action-requests/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/operations/deposits/statistics",
    "source": "app/api/operations/deposits/statistics/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/operations/ledger",
    "source": "app/api/operations/ledger/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/organization/customers",
    "source": "app/api/organization/customers/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/organization/customers",
    "source": "app/api/organization/customers/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/organization/customers/:id/notes",
    "source": "app/api/organization/customers/[id]/notes/route.ts"
  },
  {
    "method": "DELETE",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/organization/members/:id/activate",
    "source": "app/api/organization/members/[id]/activate/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/platform-strategies/:code/follow",
    "source": "app/api/platform-strategies/[code]/follow/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/platform-strategy-subscriptions/:id",
    "source": "app/api/platform-strategy-subscriptions/[id]/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/platform/network",
    "source": "app/api/platform/network/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/platform/settings",
    "source": "app/api/platform/settings/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/portfolio",
    "source": "app/api/portfolio/route.ts"
  },
  {
    "method": "DELETE",
    "route": "/api/portfolio/strategies",
    "source": "app/api/portfolio/strategies/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/portfolio/strategies",
    "source": "app/api/portfolio/strategies/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/portfolio/strategies",
    "source": "app/api/portfolio/strategies/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/public-pool",
    "source": "app/api/public-pool/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/reports/monthly",
    "source": "app/api/reports/monthly/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/risk/status",
    "source": "app/api/risk/status/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/simulated-orders",
    "source": "app/api/simulated-orders/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/simulated-orders",
    "source": "app/api/simulated-orders/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/simulated-orders/:id",
    "source": "app/api/simulated-orders/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategies/:strategyId/versions/:versionId/deployments",
    "source": "app/api/strategies/[strategyId]/versions/[versionId]/deployments/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-deployments/:id",
    "source": "app/api/strategy-deployments/[id]/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-deployments/:id/cycles",
    "source": "app/api/strategy-deployments/[id]/cycles/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-deployments/:id/pause",
    "source": "app/api/strategy-deployments/[id]/pause/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-deployments/:id/resume",
    "source": "app/api/strategy-deployments/[id]/resume/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-marketplace",
    "source": "app/api/strategy-marketplace/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace",
    "source": "app/api/strategy-marketplace/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-marketplace/:id",
    "source": "app/api/strategy-marketplace/[id]/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/strategy-marketplace/:id",
    "source": "app/api/strategy-marketplace/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/backtest",
    "source": "app/api/strategy-marketplace/[id]/backtest/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-marketplace/:id/change-request",
    "source": "app/api/strategy-marketplace/[id]/change-request/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/strategy-marketplace/:id/change-request",
    "source": "app/api/strategy-marketplace/[id]/change-request/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/change-request",
    "source": "app/api/strategy-marketplace/[id]/change-request/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/follow",
    "source": "app/api/strategy-marketplace/[id]/follow/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/submit",
    "source": "app/api/strategy-marketplace/[id]/submit/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/versions",
    "source": "app/api/strategy-marketplace/[id]/versions/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/refresh-inactive",
    "source": "app/api/strategy-marketplace/refresh-inactive/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/roles",
    "source": "app/api/strategy-research/roles/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/runs",
    "source": "app/api/strategy-research/runs/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs",
    "source": "app/api/strategy-research/runs/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/runs/:id",
    "source": "app/api/strategy-research/runs/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs/:id/answer",
    "source": "app/api/strategy-research/runs/[id]/answer/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs/:id/cancel",
    "source": "app/api/strategy-research/runs/[id]/cancel/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs/:id/candidates/:candidateId/save",
    "source": "app/api/strategy-research/runs/[id]/candidates/[candidateId]/save/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/runs/:id/events",
    "source": "app/api/strategy-research/runs/[id]/events/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-studio/chat",
    "source": "app/api/strategy-studio/chat/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/strategy-studio/generate",
    "source": "app/api/strategy-studio/generate/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/strategy-subscriptions/:id",
    "source": "app/api/strategy-subscriptions/[id]/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/system/bootstrap",
    "source": "app/api/system/bootstrap/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/team/daily-brief",
    "source": "app/api/team/daily-brief/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/team/daily-brief",
    "source": "app/api/team/daily-brief/route.ts"
  },
  {
    "method": "PUT",
    "route": "/api/team/daily-brief",
    "source": "app/api/team/daily-brief/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/team/monthly-targets",
    "source": "app/api/team/monthly-targets/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/team/monthly-targets",
    "source": "app/api/team/monthly-targets/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/team/monthly-targets/export",
    "source": "app/api/team/monthly-targets/export/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/team/monthly-targets/follow-up",
    "source": "app/api/team/monthly-targets/follow-up/route.ts"
  },
  {
    "method": "PATCH",
    "route": "/api/team/monthly-targets/follow-up",
    "source": "app/api/team/monthly-targets/follow-up/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/team/monthly-targets/follow-up",
    "source": "app/api/team/monthly-targets/follow-up/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/trading-hall",
    "source": "app/api/trading-hall/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/trading/emergency-stop",
    "source": "app/api/trading/emergency-stop/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/wallet/balances",
    "source": "app/api/wallet/balances/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/wallet/deposit-orders",
    "source": "app/api/wallet/deposit-orders/route.ts"
  },
  {
    "method": "POST",
    "route": "/api/wallet/deposit-orders",
    "source": "app/api/wallet/deposit-orders/route.ts"
  },
  {
    "method": "GET",
    "route": "/api/wallet/ledger",
    "source": "app/api/wallet/ledger/route.ts"
  }
] as const satisfies readonly ApiRouteInventoryEntry[];
