// Generated by scripts/generate-api-route-inventory.mjs. Do not edit by hand.
import type { AppAudience } from "./riverton-apps.ts";

export type ApiRouteInventoryEntry = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
  route: string;
  source: string;
  audiences: readonly AppAudience[];
  authentication: "anonymous" | "session" | "permission" | "webhook" | "bootstrap" | "disabled";
  sessionAuthHelpers: readonly string[];
  permissionKeys: readonly string[];
  permissionMfa: Readonly<Record<string, "none" | "recent">>;
  scope: "none" | "grant" | "platform";
  mfa: "none" | "recent" | "conditional";
  pii: "none" | "masked" | "full";
  sensitivity: "normal" | "sensitive";
  requiresSameOrigin: boolean;
};

export const API_ROUTE_INVENTORY = [
  {
    "method": "GET",
    "route": "/api/access/assignments",
    "source": "app/api/access/assignments/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/access/assignments",
    "source": "app/api/access/assignments/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.manage",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.manage": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "DELETE",
    "route": "/api/access/assignments/:id",
    "source": "app/api/access/assignments/[id]/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.manage",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.manage": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/access/audit",
    "source": "app/api/access/audit/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.audit.view",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.audit.view": "none",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "conditional",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/access/change-requests",
    "source": "app/api/access/change-requests/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/access/change-requests",
    "source": "app/api/access/change-requests/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/access/change-requests/:id/decisions",
    "source": "app/api/access/change-requests/[id]/decisions/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/access/me/effective",
    "source": "app/api/access/me/effective/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/access/permissions",
    "source": "app/api/access/permissions/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/access/role-templates",
    "source": "app/api/access/role-templates/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/access/role-templates",
    "source": "app/api/access/role-templates/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.manage",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.manage": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/access/roles",
    "source": "app/api/access/roles/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.approve_sensitive",
      "maint.roles.manage",
      "ops.roles.approve_sensitive",
      "ops.roles.assign",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.approve_sensitive": "recent",
      "maint.roles.manage": "recent",
      "ops.roles.approve_sensitive": "recent",
      "ops.roles.assign": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/access/roles",
    "source": "app/api/access/roles/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.manage",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.manage": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "PATCH",
    "route": "/api/access/roles/:id",
    "source": "app/api/access/roles/[id]/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.manage",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.manage": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/access/roles/:id/publish",
    "source": "app/api/access/roles/[id]/publish/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.roles.manage",
      "ops.roles.manage"
    ],
    "permissionMfa": {
      "maint.roles.manage": "recent",
      "ops.roles.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/account/llm-config",
    "source": "app/api/account/llm-config/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/account/llm-config",
    "source": "app/api/account/llm-config/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/account/llm-config/test",
    "source": "app/api/account/llm-config/test/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/account/password",
    "source": "app/api/account/password/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/account/profile",
    "source": "app/api/account/profile/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/account/profile",
    "source": "app/api/account/profile/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/admin/agent-role-bindings",
    "source": "app/api/admin/agent-role-bindings/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.agent_bindings.manage",
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.agent_bindings.manage": "recent",
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "conditional",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/admin/agent-role-bindings",
    "source": "app/api/admin/agent-role-bindings/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.agent_bindings.manage"
    ],
    "permissionMfa": {
      "maint.agent_bindings.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/admin/agent-role-bindings/test",
    "source": "app/api/admin/agent-role-bindings/test/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.agent_bindings.manage"
    ],
    "permissionMfa": {
      "maint.agent_bindings.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/admin/follow-policy",
    "source": "app/api/admin/follow-policy/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.follow_policy.view"
    ],
    "permissionMfa": {
      "maint.follow_policy.view": "none"
    },
    "scope": "platform",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/admin/follow-policy",
    "source": "app/api/admin/follow-policy/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.follow_policy.manage"
    ],
    "permissionMfa": {
      "maint.follow_policy.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/admin/llm-config",
    "source": "app/api/admin/llm-config/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/admin/llm-config",
    "source": "app/api/admin/llm-config/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.llm_profiles.manage"
    ],
    "permissionMfa": {
      "maint.llm_profiles.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/admin/llm-config/test",
    "source": "app/api/admin/llm-config/test/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.llm_profiles.manage"
    ],
    "permissionMfa": {
      "maint.llm_profiles.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/admin/llm-profiles",
    "source": "app/api/admin/llm-profiles/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.llm_profiles.manage",
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.llm_profiles.manage": "recent",
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "conditional",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/admin/llm-profiles",
    "source": "app/api/admin/llm-profiles/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.llm_profiles.manage"
    ],
    "permissionMfa": {
      "maint.llm_profiles.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "PATCH",
    "route": "/api/admin/llm-profiles/:id",
    "source": "app/api/admin/llm-profiles/[id]/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.llm_profiles.manage"
    ],
    "permissionMfa": {
      "maint.llm_profiles.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/admin/runtime-explanation-bindings",
    "source": "app/api/admin/runtime-explanation-bindings/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.agent_bindings.manage",
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.agent_bindings.manage": "recent",
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "conditional",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/admin/runtime-explanation-bindings",
    "source": "app/api/admin/runtime-explanation-bindings/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.agent_bindings.manage"
    ],
    "permissionMfa": {
      "maint.agent_bindings.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/admin/runtime-explanation-bindings/test",
    "source": "app/api/admin/runtime-explanation-bindings/test/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.agent_bindings.manage"
    ],
    "permissionMfa": {
      "maint.agent_bindings.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/ai/conversations",
    "source": "app/api/ai/conversations/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/ai/conversations",
    "source": "app/api/ai/conversations/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/ai/conversations/:id",
    "source": "app/api/ai/conversations/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/ai/conversations/:id",
    "source": "app/api/ai/conversations/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/ai/conversations/:id/messages",
    "source": "app/api/ai/conversations/[id]/messages/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/ai/conversations/:id/messages/:messageId/strategy",
    "source": "app/api/ai/conversations/[id]/messages/[messageId]/strategy/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/approvals",
    "source": "app/api/approvals/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.approvals.view"
    ],
    "permissionMfa": {
      "ops.approvals.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/approvals/:id/decision",
    "source": "app/api/approvals/[id]/decision/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.approvals.decide"
    ],
    "permissionMfa": {
      "ops.approvals.decide": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/attributions/requests",
    "source": "app/api/attributions/requests/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.attributions.manage"
    ],
    "permissionMfa": {
      "ops.attributions.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/attributions/transfers",
    "source": "app/api/attributions/transfers/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.attributions.manage"
    ],
    "permissionMfa": {
      "ops.attributions.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/forgot-password",
    "source": "app/api/auth/forgot-password/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/login",
    "source": "app/api/auth/login/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/logout",
    "source": "app/api/auth/logout/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/auth/me",
    "source": "app/api/auth/me/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/auth/mfa/enroll/confirm",
    "source": "app/api/auth/mfa/enroll/confirm/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requirePrimarySession"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/mfa/enroll/start",
    "source": "app/api/auth/mfa/enroll/start/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requirePrimarySession"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/mfa/verify",
    "source": "app/api/auth/mfa/verify/route.ts",
    "audiences": [
      "operations",
      "maintenance"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requirePrimarySession"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/register",
    "source": "app/api/auth/register/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/reset-password",
    "source": "app/api/auth/reset-password/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/auth/verify-email",
    "source": "app/api/auth/verify-email/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/automation/demo-cycle",
    "source": "app/api/automation/demo-cycle/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/automation/platform-ai-cycle",
    "source": "app/api/automation/platform-ai-cycle/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/credits/me",
    "source": "app/api/credits/me/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.credits.view"
    ],
    "permissionMfa": {
      "client.credits.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/data-center",
    "source": "app/api/data-center/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.customers.view"
    ],
    "permissionMfa": {
      "ops.customers.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/employee/tasks",
    "source": "app/api/employee/tasks/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.view"
    ],
    "permissionMfa": {
      "ops.team.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/exchange-accounts",
    "source": "app/api/exchange-accounts/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/exchange-accounts",
    "source": "app/api/exchange-accounts/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "PATCH",
    "route": "/api/exchange-accounts/:id",
    "source": "app/api/exchange-accounts/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/exchange-accounts/:id/perpetual-instruments",
    "source": "app/api/exchange-accounts/[id]/perpetual-instruments/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/exchange-accounts/:id/routing",
    "source": "app/api/exchange-accounts/[id]/routing/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/finance/adjustments",
    "source": "app/api/finance/adjustments/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.reconciliation.run"
    ],
    "permissionMfa": {
      "ops.reconciliation.run": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/finance/collections",
    "source": "app/api/finance/collections/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.ledger.view"
    ],
    "permissionMfa": {
      "ops.ledger.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/finance/collections/:id/confirm-paid",
    "source": "app/api/finance/collections/[id]/confirm-paid/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.finance.manage"
    ],
    "permissionMfa": {
      "ops.finance.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/finance/collections/refresh",
    "source": "app/api/finance/collections/refresh/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.finance.manage"
    ],
    "permissionMfa": {
      "ops.finance.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/finance/payout-profiles",
    "source": "app/api/finance/payout-profiles/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.ledger.view"
    ],
    "permissionMfa": {
      "ops.ledger.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/finance/payout-profiles",
    "source": "app/api/finance/payout-profiles/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.reconciliation.run"
    ],
    "permissionMfa": {
      "ops.reconciliation.run": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "full",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/finance/settlements",
    "source": "app/api/finance/settlements/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.ledger.view"
    ],
    "permissionMfa": {
      "ops.ledger.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/finance/settlements",
    "source": "app/api/finance/settlements/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.reconciliation.run"
    ],
    "permissionMfa": {
      "ops.reconciliation.run": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/finance/settlements/:id/paid",
    "source": "app/api/finance/settlements/[id]/paid/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.finance.manage"
    ],
    "permissionMfa": {
      "ops.finance.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/health",
    "source": "app/api/health/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/health/live",
    "source": "app/api/health/live/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/health/ready",
    "source": "app/api/health/ready/route.ts",
    "audiences": [
      "client",
      "operations",
      "maintenance"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/integrations/catalog",
    "source": "app/api/integrations/catalog/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/integrations/payments/:provider/webhook",
    "source": "app/api/integrations/payments/[provider]/webhook/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "disabled",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/integrations/resend/webhook",
    "source": "app/api/integrations/resend/webhook/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "webhook",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/invitations",
    "source": "app/api/invitations/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.invitations.view"
    ],
    "permissionMfa": {
      "ops.invitations.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/invitations",
    "source": "app/api/invitations/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.invitations.manage"
    ],
    "permissionMfa": {
      "ops.invitations.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/maintenance/demo-exchanges",
    "source": "app/api/maintenance/demo-exchanges/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.demo_exchanges.view"
    ],
    "permissionMfa": {
      "maint.demo_exchanges.view": "none"
    },
    "scope": "platform",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/maintenance/demo-exchanges/:id/control",
    "source": "app/api/maintenance/demo-exchanges/[id]/control/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.demo_exchanges.kill",
      "maint.demo_exchanges.manage"
    ],
    "permissionMfa": {
      "maint.demo_exchanges.kill": "recent",
      "maint.demo_exchanges.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/maintenance/demo-exchanges/:id/verify",
    "source": "app/api/maintenance/demo-exchanges/[id]/verify/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.demo_exchanges.verify"
    ],
    "permissionMfa": {
      "maint.demo_exchanges.verify": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/maintenance/email/status",
    "source": "app/api/maintenance/email/status/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.email_integrations.manage",
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.email_integrations.manage": "recent",
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "conditional",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/maintenance/email/test",
    "source": "app/api/maintenance/email/test/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.email_integrations.manage"
    ],
    "permissionMfa": {
      "maint.email_integrations.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/maintenance/payment-providers",
    "source": "app/api/maintenance/payment-providers/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.payment_integrations.manage",
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.payment_integrations.manage": "recent",
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "conditional",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/maintenance/payment-providers/:id/status",
    "source": "app/api/maintenance/payment-providers/[id]/status/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.payment_integrations.manage"
    ],
    "permissionMfa": {
      "maint.payment_integrations.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/maintenance/payment-providers/:id/test",
    "source": "app/api/maintenance/payment-providers/[id]/test/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.payment_integrations.manage"
    ],
    "permissionMfa": {
      "maint.payment_integrations.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/maintenance/payment-workers/health",
    "source": "app/api/maintenance/payment-workers/health/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.system_health.view"
    ],
    "permissionMfa": {
      "maint.system_health.view": "none"
    },
    "scope": "platform",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/maintenance/platform-settings",
    "source": "app/api/maintenance/platform-settings/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.feature_flags.manage"
    ],
    "permissionMfa": {
      "maint.feature_flags.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/maintenance/platform-settings",
    "source": "app/api/maintenance/platform-settings/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.feature_flags.manage"
    ],
    "permissionMfa": {
      "maint.feature_flags.manage": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/maintenance/trading/emergency-stop",
    "source": "app/api/maintenance/trading/emergency-stop/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.emergency_pause.execute"
    ],
    "permissionMfa": {
      "maint.emergency_pause.execute": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/maintenance/trading/emergency-stop",
    "source": "app/api/maintenance/trading/emergency-stop/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "maint.emergency_pause.execute"
    ],
    "permissionMfa": {
      "maint.emergency_pause.execute": "recent"
    },
    "scope": "platform",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/market/candles",
    "source": "app/api/market/candles/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/market/instruments",
    "source": "app/api/market/instruments/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/market/news",
    "source": "app/api/market/news/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/market/quote",
    "source": "app/api/market/quote/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/market/ticker",
    "source": "app/api/market/ticker/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "DELETE",
    "route": "/api/market/watchlist",
    "source": "app/api/market/watchlist/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/market/watchlist",
    "source": "app/api/market/watchlist/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/market/watchlist",
    "source": "app/api/market/watchlist/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/membership/me",
    "source": "app/api/membership/me/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.membership.view"
    ],
    "permissionMfa": {
      "client.membership.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/membership/orders",
    "source": "app/api/membership/orders/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.membership.view"
    ],
    "permissionMfa": {
      "client.membership.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/membership/orders",
    "source": "app/api/membership/orders/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.membership.order"
    ],
    "permissionMfa": {
      "client.membership.order": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/membership/performance-statements",
    "source": "app/api/membership/performance-statements/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.membership.view"
    ],
    "permissionMfa": {
      "client.membership.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/membership/plans",
    "source": "app/api/membership/plans/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.membership.view"
    ],
    "permissionMfa": {
      "client.membership.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/notifications/channels",
    "source": "app/api/notifications/channels/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/notifications/channels",
    "source": "app/api/notifications/channels/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/notifications/channels",
    "source": "app/api/notifications/channels/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/notifications/inbox",
    "source": "app/api/notifications/inbox/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/notifications/inbox",
    "source": "app/api/notifications/inbox/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/notifications/preferences",
    "source": "app/api/notifications/preferences/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PUT",
    "route": "/api/notifications/preferences",
    "source": "app/api/notifications/preferences/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/operations/credits",
    "source": "app/api/operations/credits/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.credits.view"
    ],
    "permissionMfa": {
      "ops.credits.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/operations/deposit-action-requests",
    "source": "app/api/operations/deposit-action-requests/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.deposits.action_approve"
    ],
    "permissionMfa": {
      "ops.deposits.action_approve": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/operations/deposit-action-requests/:id/decisions",
    "source": "app/api/operations/deposit-action-requests/[id]/decisions/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.deposits.action_approve"
    ],
    "permissionMfa": {
      "ops.deposits.action_approve": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/operations/deposits",
    "source": "app/api/operations/deposits/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.deposits.view"
    ],
    "permissionMfa": {
      "ops.deposits.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/operations/deposits/:id",
    "source": "app/api/operations/deposits/[id]/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.deposits.view"
    ],
    "permissionMfa": {
      "ops.deposits.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/operations/deposits/:id/action-requests",
    "source": "app/api/operations/deposits/[id]/action-requests/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.deposits.action_request"
    ],
    "permissionMfa": {
      "ops.deposits.action_request": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "full",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/operations/deposits/statistics",
    "source": "app/api/operations/deposits/statistics/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.deposits.view"
    ],
    "permissionMfa": {
      "ops.deposits.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/operations/ledger",
    "source": "app/api/operations/ledger/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.ledger.view"
    ],
    "permissionMfa": {
      "ops.ledger.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/operations/membership-orders",
    "source": "app/api/operations/membership-orders/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.membership_orders.view"
    ],
    "permissionMfa": {
      "ops.membership_orders.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/operations/membership-orders/:id",
    "source": "app/api/operations/membership-orders/[id]/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.membership_orders.view"
    ],
    "permissionMfa": {
      "ops.membership_orders.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/operations/membership-orders/:id/decision",
    "source": "app/api/operations/membership-orders/[id]/decision/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.membership_orders.approve"
    ],
    "permissionMfa": {
      "ops.membership_orders.approve": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/operations/membership-orders/:id/evidence",
    "source": "app/api/operations/membership-orders/[id]/evidence/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.membership_orders.evidence"
    ],
    "permissionMfa": {
      "ops.membership_orders.evidence": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/operations/membership-orders/:id/submit",
    "source": "app/api/operations/membership-orders/[id]/submit/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.membership_orders.evidence"
    ],
    "permissionMfa": {
      "ops.membership_orders.evidence": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/operations/performance-statements",
    "source": "app/api/operations/performance-statements/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.performance_fees.view"
    ],
    "permissionMfa": {
      "ops.performance_fees.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/operations/performance-statements/:id",
    "source": "app/api/operations/performance-statements/[id]/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.performance_fees.view"
    ],
    "permissionMfa": {
      "ops.performance_fees.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/operations/performance-statements/:id/decision",
    "source": "app/api/operations/performance-statements/[id]/decision/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.performance_fees.approve"
    ],
    "permissionMfa": {
      "ops.performance_fees.approve": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/operations/performance-statements/:id/payment-decision",
    "source": "app/api/operations/performance-statements/[id]/payment-decision/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.performance_fees.payment_approve"
    ],
    "permissionMfa": {
      "ops.performance_fees.payment_approve": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/operations/performance-statements/:id/payment-evidence",
    "source": "app/api/operations/performance-statements/[id]/payment-evidence/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.performance_fees.payment_evidence"
    ],
    "permissionMfa": {
      "ops.performance_fees.payment_evidence": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/operations/performance-statements/generate",
    "source": "app/api/operations/performance-statements/generate/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.performance_fees.generate"
    ],
    "permissionMfa": {
      "ops.performance_fees.generate": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/organization/customers",
    "source": "app/api/organization/customers/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.customers.view"
    ],
    "permissionMfa": {
      "ops.customers.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "masked",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/organization/customers",
    "source": "app/api/organization/customers/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.customers.manage"
    ],
    "permissionMfa": {
      "ops.customers.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "masked",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/organization/customers/:id/notes",
    "source": "app/api/organization/customers/[id]/notes/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.customers.manage"
    ],
    "permissionMfa": {
      "ops.customers.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "masked",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "DELETE",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.organization.manage"
    ],
    "permissionMfa": {
      "ops.organization.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "full",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.organization.view"
    ],
    "permissionMfa": {
      "ops.organization.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "full",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.organization.manage"
    ],
    "permissionMfa": {
      "ops.organization.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "full",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/organization/members",
    "source": "app/api/organization/members/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.organization.manage"
    ],
    "permissionMfa": {
      "ops.organization.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "full",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/organization/members/:id/activate",
    "source": "app/api/organization/members/[id]/activate/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.organization.manage"
    ],
    "permissionMfa": {
      "ops.organization.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/platform-strategies/:code/follow",
    "source": "app/api/platform-strategies/[code]/follow/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.paper.manage"
    ],
    "permissionMfa": {
      "client.paper.manage": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "PATCH",
    "route": "/api/platform-strategy-subscriptions/:id",
    "source": "app/api/platform-strategy-subscriptions/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/platform/network",
    "source": "app/api/platform/network/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/platform/settings",
    "source": "app/api/platform/settings/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/portfolio",
    "source": "app/api/portfolio/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "DELETE",
    "route": "/api/portfolio/strategies",
    "source": "app/api/portfolio/strategies/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/portfolio/strategies",
    "source": "app/api/portfolio/strategies/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/portfolio/strategies",
    "source": "app/api/portfolio/strategies/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/public-pool",
    "source": "app/api/public-pool/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.customers.view"
    ],
    "permissionMfa": {
      "ops.customers.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/reports/monthly",
    "source": "app/api/reports/monthly/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.ledger.view"
    ],
    "permissionMfa": {
      "ops.ledger.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/risk/status",
    "source": "app/api/risk/status/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/simulated-orders",
    "source": "app/api/simulated-orders/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/simulated-orders",
    "source": "app/api/simulated-orders/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "PATCH",
    "route": "/api/simulated-orders/:id",
    "source": "app/api/simulated-orders/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategies/:strategyId/versions/:versionId/deployments",
    "source": "app/api/strategies/[strategyId]/versions/[versionId]/deployments/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-deployments/:id",
    "source": "app/api/strategy-deployments/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/strategy-deployments/:id/cycles",
    "source": "app/api/strategy-deployments/[id]/cycles/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/strategy-deployments/:id/pause",
    "source": "app/api/strategy-deployments/[id]/pause/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-deployments/:id/resume",
    "source": "app/api/strategy-deployments/[id]/resume/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-marketplace",
    "source": "app/api/strategy-marketplace/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace",
    "source": "app/api/strategy-marketplace/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-marketplace/:id",
    "source": "app/api/strategy-marketplace/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/strategy-marketplace/:id",
    "source": "app/api/strategy-marketplace/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/backtest",
    "source": "app/api/strategy-marketplace/[id]/backtest/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-marketplace/:id/change-request",
    "source": "app/api/strategy-marketplace/[id]/change-request/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/strategy-marketplace/:id/change-request",
    "source": "app/api/strategy-marketplace/[id]/change-request/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/change-request",
    "source": "app/api/strategy-marketplace/[id]/change-request/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/follow",
    "source": "app/api/strategy-marketplace/[id]/follow/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/submit",
    "source": "app/api/strategy-marketplace/[id]/submit/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/:id/versions",
    "source": "app/api/strategy-marketplace/[id]/versions/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-marketplace/refresh-inactive",
    "source": "app/api/strategy-marketplace/refresh-inactive/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/roles",
    "source": "app/api/strategy-research/roles/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/runs",
    "source": "app/api/strategy-research/runs/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs",
    "source": "app/api/strategy-research/runs/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/runs/:id",
    "source": "app/api/strategy-research/runs/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs/:id/answer",
    "source": "app/api/strategy-research/runs/[id]/answer/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs/:id/cancel",
    "source": "app/api/strategy-research/runs/[id]/cancel/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-research/runs/:id/candidates/:candidateId/save",
    "source": "app/api/strategy-research/runs/[id]/candidates/[candidateId]/save/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/strategy-research/runs/:id/events",
    "source": "app/api/strategy-research/runs/[id]/events/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireResearchUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/strategy-studio/chat",
    "source": "app/api/strategy-studio/chat/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "anonymous",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/strategy-studio/generate",
    "source": "app/api/strategy-studio/generate/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAiCustomer"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "PATCH",
    "route": "/api/strategy-subscriptions/:id",
    "source": "app/api/strategy-subscriptions/[id]/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/system/bootstrap",
    "source": "app/api/system/bootstrap/route.ts",
    "audiences": [
      "maintenance"
    ],
    "authentication": "bootstrap",
    "sessionAuthHelpers": [],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "sensitive",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/team/daily-brief",
    "source": "app/api/team/daily-brief/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.view"
    ],
    "permissionMfa": {
      "ops.team.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "masked",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/team/daily-brief",
    "source": "app/api/team/daily-brief/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.manage"
    ],
    "permissionMfa": {
      "ops.team.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "masked",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "PUT",
    "route": "/api/team/daily-brief",
    "source": "app/api/team/daily-brief/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.view"
    ],
    "permissionMfa": {
      "ops.team.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "masked",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/team/monthly-targets",
    "source": "app/api/team/monthly-targets/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.view"
    ],
    "permissionMfa": {
      "ops.team.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "masked",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/team/monthly-targets",
    "source": "app/api/team/monthly-targets/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.manage"
    ],
    "permissionMfa": {
      "ops.team.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "masked",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/team/monthly-targets/export",
    "source": "app/api/team/monthly-targets/export/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.view"
    ],
    "permissionMfa": {
      "ops.team.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "masked",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/team/monthly-targets/follow-up",
    "source": "app/api/team/monthly-targets/follow-up/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.view"
    ],
    "permissionMfa": {
      "ops.team.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "masked",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "PATCH",
    "route": "/api/team/monthly-targets/follow-up",
    "source": "app/api/team/monthly-targets/follow-up/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.manage"
    ],
    "permissionMfa": {
      "ops.team.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "masked",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "POST",
    "route": "/api/team/monthly-targets/follow-up",
    "source": "app/api/team/monthly-targets/follow-up/route.ts",
    "audiences": [
      "operations"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "ops.team.manage"
    ],
    "permissionMfa": {
      "ops.team.manage": "recent"
    },
    "scope": "grant",
    "mfa": "recent",
    "pii": "masked",
    "sensitivity": "sensitive",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/trading-hall",
    "source": "app/api/trading-hall/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.paper.view"
    ],
    "permissionMfa": {
      "client.paper.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/trading-hall/paper/portfolio",
    "source": "app/api/trading-hall/paper/portfolio/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.paper.view"
    ],
    "permissionMfa": {
      "client.paper.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/trading-hall/paper/trades",
    "source": "app/api/trading-hall/paper/trades/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "permission",
    "sessionAuthHelpers": [],
    "permissionKeys": [
      "client.paper.view"
    ],
    "permissionMfa": {
      "client.paper.view": "none"
    },
    "scope": "grant",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/trading/emergency-stop",
    "source": "app/api/trading/emergency-stop/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireUser"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/wallet/balances",
    "source": "app/api/wallet/balances/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAccessPermission"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "GET",
    "route": "/api/wallet/deposit-orders",
    "source": "app/api/wallet/deposit-orders/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAccessPermission"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  },
  {
    "method": "POST",
    "route": "/api/wallet/deposit-orders",
    "source": "app/api/wallet/deposit-orders/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAccessPermission"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": true
  },
  {
    "method": "GET",
    "route": "/api/wallet/ledger",
    "source": "app/api/wallet/ledger/route.ts",
    "audiences": [
      "client"
    ],
    "authentication": "session",
    "sessionAuthHelpers": [
      "requireAccessPermission"
    ],
    "permissionKeys": [],
    "permissionMfa": {},
    "scope": "none",
    "mfa": "none",
    "pii": "none",
    "sensitivity": "normal",
    "requiresSameOrigin": false
  }
] as const satisfies readonly ApiRouteInventoryEntry[];
