const membershipStatuses={pending_evidence:"awaitingPaymentEvidence",pending_review:"awaitingApproval",activated:"activated",rejected:"rejected",cancelled:"cancelled"} as const;
const performanceStatuses={pending_review:"awaitingAssessment",payment_pending:"awaitingPaymentConfirmation",paid:"paid",no_fee:"closedNoFee",rejected:"rejected"} as const;

export function publicMembershipOrderStatus(status:string){const value=membershipStatuses[status as keyof typeof membershipStatuses];if(!value)throw new Error("UNKNOWN_MEMBERSHIP_ORDER_STATUS");return value;}
export function publicPerformanceStatementStatus(status:string){const value=performanceStatuses[status as keyof typeof performanceStatuses];if(!value)throw new Error("UNKNOWN_PERFORMANCE_STATEMENT_STATUS");return value;}

export function membershipOrderDto(row:Record<string,unknown>){return {id:String(row.id),orderNo:String(row.order_no),userId:row.user_id?String(row.user_id):undefined,planVersionId:String(row.plan_version_id),price:{amount:String(row.price_amount),currency:String(row.price_currency)},status:publicMembershipOrderStatus(String(row.status)),createdAt:new Date(row.created_at as string|Date).toISOString(),updatedAt:row.updated_at?new Date(row.updated_at as string|Date).toISOString():undefined};}
export function performanceStatementDto(row:Record<string,unknown>){return {id:String(row.id),userId:row.user_id?String(row.user_id):undefined,weekStart:new Date(row.week_start as string|Date).toISOString(),weekEnd:new Date(row.week_end as string|Date).toISOString(),weekNetPnl:String(row.week_net_pnl),eligibleProfit:String(row.eligible_profit),lossCarry:String(row.loss_carry),feeBps:Number(row.fee_bps),feeAmount:String(row.fee_amount),currency:String(row.currency),status:publicPerformanceStatementStatus(String(row.status)),createdAt:new Date(row.created_at as string|Date).toISOString()};}
export function membershipActionDto(value:unknown){const row=value as Record<string,unknown>;return {...row,status:publicMembershipOrderStatus(String(row.status))};}
export function performanceActionDto(value:unknown){const row=value as Record<string,unknown>;return {...row,status:publicPerformanceStatementStatus(String(row.status))};}
