export type IntegrationCategory = "market" | "news" | "ai" | "search";

export type IntegrationDefinition = {
  id: string;
  category: IntegrationCategory;
  name: string;
  description: string;
  freeTier: string;
  requiresKey: boolean;
  envKeys: string[];
  docsUrl: string;
  status: "wired" | "ready-to-configure" | "catalog-only";
  serverOnly: boolean;
};

/**
 * This is a safe, non-secret catalog. It tells an operator what can be
 * connected and where the value belongs; it never contains a credential.
 * "Free" means public access or a provider free tier, not unlimited usage.
 */
export const INTEGRATION_CATALOG: IntegrationDefinition[] = [
  {
    id: "multi-exchange-public-market",
    category: "market",
    name: "Multi-exchange Public REST / WebSocket",
    description: "Coinbase 默认，按用户配置或页面选择交易所，提供报价、24 小时涨跌、K 线与实时行情雷达",
    freeTier: "公共行情无需 API Key",
    requiresKey: false,
    envKeys: ["MARKET_DATA_BASE_URL", "MARKET_DATA_PROVIDER"],
    docsUrl: "https://docs.cdp.coinbase.com/exchange/introduction",
    status: "wired",
    serverOnly: true,
  },
  {
    id: "coingecko",
    category: "market",
    name: "CoinGecko API",
    description: "更广的币种目录、市场总览和历史价格",
    freeTier: "提供免费额度（需遵守限流）",
    requiresKey: true,
    envKeys: ["COINGECKO_API_KEY"],
    docsUrl: "https://docs.coingecko.com/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "coincap",
    category: "market",
    name: "CoinCap API",
    description: "资产列表、价格、交易量和市场排名",
    freeTier: "公共接口或免费额度（以账户页面为准）",
    requiresKey: false,
    envKeys: ["COINCAP_API_KEY"],
    docsUrl: "https://docs.coincap.io/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "cryptocompare",
    category: "market",
    name: "CryptoCompare",
    description: "多交易所聚合报价、历史数据与指标",
    freeTier: "提供免费开发额度（需申请 Key）",
    requiresKey: true,
    envKeys: ["CRYPTOCOMPARE_API_KEY"],
    docsUrl: "https://developers.cryptocompare.com/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "twelve-data",
    category: "market",
    name: "Twelve Data",
    description: "加密资产、外汇、指数和股票的统一行情",
    freeTier: "提供免费开发额度（需申请 Key）",
    requiresKey: true,
    envKeys: ["TWELVEDATA_API_KEY"],
    docsUrl: "https://twelvedata.com/docs",
    status: "catalog-only",
    serverOnly: true,
  },
  {
    id: "coindesk-rss",
    category: "news",
    name: "CoinDesk RSS",
    description: "加密市场快讯与行业新闻",
    freeTier: "公开 RSS，无需 API Key",
    requiresKey: false,
    envKeys: ["NEWS_RSS_URLS"],
    docsUrl: "https://www.coindesk.com/",
    status: "wired",
    serverOnly: true,
  },
  {
    id: "cointelegraph-rss",
    category: "news",
    name: "Cointelegraph RSS",
    description: "加密行业新闻与项目动态",
    freeTier: "公开 RSS，无需 API Key",
    requiresKey: false,
    envKeys: ["NEWS_RSS_URLS"],
    docsUrl: "https://cointelegraph.com/",
    status: "wired",
    serverOnly: true,
  },
  {
    id: "gdelt",
    category: "news",
    name: "GDELT 2.1",
    description: "全球新闻检索与事件趋势，适合雷达扩展",
    freeTier: "公开接口，无需 API Key",
    requiresKey: false,
    envKeys: ["GDELT_API_URL"],
    docsUrl: "https://www.gdeltproject.org/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "cryptopanic",
    category: "news",
    name: "CryptoPanic",
    description: "按币种聚合新闻、情绪和重要性标签",
    freeTier: "提供免费方案（需申请 Key）",
    requiresKey: true,
    envKeys: ["CRYPTOPANIC_API_KEY"],
    docsUrl: "https://cryptopanic.com/developers/api/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "newsapi",
    category: "news",
    name: "NewsAPI",
    description: "通用新闻检索，可作为行业新闻补充源",
    freeTier: "有开发者免费方案（有使用限制）",
    requiresKey: true,
    envKeys: ["NEWSAPI_KEY"],
    docsUrl: "https://newsapi.org/docs",
    status: "catalog-only",
    serverOnly: true,
  },
  {
    id: "openai-compatible",
    category: "ai",
    name: "OpenAI-compatible LLM",
    description: "策略沟通、结构化策略生成、反方审查和 Agent 决策摘要",
    freeTier: "按供应商计费；部分供应商提供试用额度",
    requiresKey: true,
    envKeys: ["AI_API_URL", "AI_API_KEY", "AI_MODEL"],
    docsUrl: "https://platform.openai.com/docs/",
    status: "wired",
    serverOnly: true,
  },
  {
    id: "deepseek",
    category: "ai",
    name: "DeepSeek",
    description: "可作为中文策略沟通与分析模型",
    freeTier: "以供应商账户页面为准",
    requiresKey: true,
    envKeys: ["DEEPSEEK_API_KEY", "AI_API_URL", "AI_MODEL"],
    docsUrl: "https://api-docs.deepseek.com/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "gemini",
    category: "ai",
    name: "Google Gemini",
    description: "多模态分析与策略研究备用模型",
    freeTier: "提供部分免费额度（以地区和账户为准）",
    requiresKey: true,
    envKeys: ["GEMINI_API_KEY"],
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    status: "catalog-only",
    serverOnly: true,
  },
  {
    id: "anthropic",
    category: "ai",
    name: "Anthropic Claude",
    description: "长上下文研究、审查和风险说明备用模型",
    freeTier: "以供应商账户页面为准",
    requiresKey: true,
    envKeys: ["ANTHROPIC_API_KEY"],
    docsUrl: "https://docs.anthropic.com/",
    status: "catalog-only",
    serverOnly: true,
  },
  {
    id: "tavily",
    category: "search",
    name: "Tavily Search",
    description: "给 Agent 提供带引用的实时网页检索",
    freeTier: "提供免费开发额度（需申请 Key）",
    requiresKey: true,
    envKeys: ["TAVILY_API_KEY"],
    docsUrl: "https://docs.tavily.com/",
    status: "ready-to-configure",
    serverOnly: true,
  },
  {
    id: "brave-search",
    category: "search",
    name: "Brave Search API",
    description: "独立搜索索引，补充新闻和项目资料检索",
    freeTier: "提供免费额度（需申请 Key）",
    requiresKey: true,
    envKeys: ["BRAVE_SEARCH_API_KEY"],
    docsUrl: "https://api.search.brave.com/app/documentation",
    status: "catalog-only",
    serverOnly: true,
  },
  {
    id: "serpapi",
    category: "search",
    name: "SerpApi",
    description: "搜索结果聚合，适合作为备用检索源",
    freeTier: "提供有限免费额度（需申请 Key）",
    requiresKey: true,
    envKeys: ["SERPAPI_KEY"],
    docsUrl: "https://serpapi.com/docs",
    status: "catalog-only",
    serverOnly: true,
  },
];

export const INTEGRATION_CATEGORY_LABELS: Record<IntegrationCategory, string> = {
  market: "行情",
  news: "新闻",
  ai: "大模型",
  search: "搜索",
};
