INSERT INTO permission_definitions (key, application_id, label, sensitive, status)
VALUES
  ('maint.commercial_disclosures.view', 'maintenance', '查看商业披露', false, 'active'),
  ('maint.commercial_disclosures.submit', 'maintenance', '提交商业披露发布', true, 'active'),
  ('maint.commercial_disclosures.approve', 'maintenance', '审批商业披露发布', true, 'active')
ON CONFLICT (key) DO UPDATE SET
  application_id = EXCLUDED.application_id,
  label = EXCLUDED.label,
  sensitive = EXCLUDED.sensitive,
  status = EXCLUDED.status,
  updated_at = now();

CREATE TABLE IF NOT EXISTS commercial_disclosure_publish_requests (
  id text PRIMARY KEY,
  locale text NOT NULL CHECK (locale ~ '^[a-z]{2}(-[A-Z]{2})?$'),
  product_identity_json jsonb NOT NULL CHECK (jsonb_typeof(product_identity_json) = 'object'),
  document_snapshot_json jsonb NOT NULL CHECK (jsonb_typeof(document_snapshot_json) = 'array'),
  snapshot_sha256 text NOT NULL CHECK (snapshot_sha256 ~ '^[a-f0-9]{64}$'),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  submitted_by_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  submission_reason text NOT NULL CHECK (char_length(submission_reason) BETWEEN 3 AND 500),
  idempotency_key text NOT NULL,
  request_id text NOT NULL,
  reviewed_by_user_id text REFERENCES users(id) ON DELETE RESTRICT,
  review_idempotency_key text,
  review_note text,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (submitted_by_user_id, idempotency_key),
  CHECK (reviewed_by_user_id IS NULL OR reviewed_by_user_id <> submitted_by_user_id),
  CHECK (
    (status = 'pending' AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL)
    OR
    (status IN ('approved','rejected') AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL AND char_length(review_note) BETWEEN 3 AND 500)
  )
);
CREATE INDEX IF NOT EXISTS idx_commercial_disclosure_requests_queue
  ON commercial_disclosure_publish_requests(status, created_at DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_commercial_disclosure_one_pending_request
  ON commercial_disclosure_publish_requests((true)) WHERE status = 'pending';
CREATE UNIQUE INDEX IF NOT EXISTS idx_commercial_disclosure_review_idempotency
  ON commercial_disclosure_publish_requests(review_idempotency_key)
  WHERE review_idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS commercial_disclosure_bundles (
  id text PRIMARY KEY,
  version bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  locale text NOT NULL CHECK (locale ~ '^[a-z]{2}(-[A-Z]{2})?$'),
  product_identity_json jsonb NOT NULL CHECK (jsonb_typeof(product_identity_json) = 'object'),
  document_snapshot_json jsonb NOT NULL CHECK (jsonb_typeof(document_snapshot_json) = 'array'),
  snapshot_sha256 text NOT NULL CHECK (snapshot_sha256 ~ '^[a-f0-9]{64}$'),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','retired')),
  publish_request_id text NOT NULL UNIQUE REFERENCES commercial_disclosure_publish_requests(id) ON DELETE RESTRICT,
  submitted_by_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  published_by_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  published_at timestamptz NOT NULL,
  retired_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (published_by_user_id <> submitted_by_user_id),
  CHECK ((status = 'active' AND retired_at IS NULL) OR (status = 'retired' AND retired_at IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_commercial_disclosure_one_active_bundle
  ON commercial_disclosure_bundles((true)) WHERE status = 'active';

ALTER TABLE commercial_legal_document_versions
  ADD COLUMN IF NOT EXISTS bundle_id text REFERENCES commercial_disclosure_bundles(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_commercial_legal_bundle
  ON commercial_legal_document_versions(bundle_id, document_type);

CREATE TABLE IF NOT EXISTS membership_access_events (
  id text PRIMARY KEY,
  membership_id text NOT NULL REFERENCES memberships(id) ON DELETE RESTRICT,
  customer_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  event_type text NOT NULL CHECK (event_type IN ('trial_started','trial_grace_started','membership_grace_started','read_only_started','membership_expired','membership_restored')),
  effective_at timestamptz NOT NULL,
  state_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(state_json) = 'object'),
  dedupe_key text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_membership_access_events_customer_time
  ON membership_access_events(customer_id, effective_at DESC, id DESC);

COMMENT ON TABLE commercial_disclosure_publish_requests IS
  'Platform-managed commercial disclosure submissions. Approval records product publication; it is not represented as external legal advice.';
COMMENT ON TABLE commercial_legal_acceptances IS
  'Immutable customer acceptance evidence for the exact active disclosure document versions.';
