import { requireAccessPermission } from "@/lib/access-control";
import { commercialJson,commercialListInput,idempotencyKey,requestId,requiredString,stringArray } from "@/lib/commercial-api";
import { encodeCommercialCursor } from "@/lib/commercial-api-support";
import { createMembershipOrder } from "@/lib/commercial-membership-service";
import { membershipOrderDto } from "@/lib/commercial-public-contract";
import { getPostgresPool } from "@/lib/postgres";
import { researchErrorResponse } from "@/lib/research-api";

export async function GET(request:Request){try{const {user}=await requireAccessPermission(request,"client.membership.view");const {limit,cursor}=commercialListInput(request);const params:unknown[]=[user.id];let cursorSql="";if(cursor){params.push(cursor.createdAt,cursor.id);cursorSql=`AND (o.created_at,o.id)<($2::timestamptz,$3)`;}params.push(limit+1);const result=await (await getPostgresPool()).query(`SELECT o.id,o.order_no,o.user_id,o.plan_version_id,o.price_amount::text,o.price_currency,o.status,o.created_at,o.updated_at FROM commercial_membership_orders o WHERE o.user_id=$1 ${cursorSql} ORDER BY o.created_at DESC,o.id DESC LIMIT $${params.length}`,params);const rows=result.rows.slice(0,limit),last=rows.at(-1);return Response.json({orders:rows.map(membershipOrderDto),nextCursor:result.rows.length>limit&&last?encodeCommercialCursor({createdAt:new Date(last.created_at).toISOString(),id:last.id}):null},{headers:{"cache-control":"no-store"}});}catch(error){return researchErrorResponse(error);}}
export async function POST(request:Request){try{const {user}=await requireAccessPermission(request,"client.membership.order");const body=await commercialJson(request);const row=await createMembershipOrder(await getPostgresPool(),{userId:user.id,planVersionId:requiredString(body,"planVersionId",100),acceptedDocumentVersionIds:stringArray(body,"acceptedDocumentVersionIds",7),idempotencyKey:idempotencyKey(request),requestId:requestId(request),ipAddress:request.headers.get("x-forwarded-for")?.split(",")[0]?.trim(),userAgent:request.headers.get("user-agent")??undefined});return Response.json({order:membershipOrderDto(row)},{status:201});}catch(error){return researchErrorResponse(error);}}
