import { fetchPublicMarketJson, publicMarketProviderName } from "@/lib/public-market-source";

type Category = "crypto" | "forex" | "metals" | "stocks";
type Candle = { time: number; open: number; high: number; low: number; close: number; volume: number };
const yahooSymbols: Record<string, string> = { EURUSD: "EURUSD=X", GBPUSD: "GBPUSD=X", USDJPY: "JPY=X", AUDUSD: "AUDUSD=X", USDCAD: "CAD=X", USDCHF: "CHF=X", NZDUSD: "NZDUSD=X", EURJPY: "EURJPY=X", GBPJPY: "GBPJPY=X", XAUUSD: "GC=F", XAGUSD: "SI=F" };
const binanceIntervals: Record<string, string> = { "1m": "1m", "5m": "5m", "15m": "15m", "30m": "30m", "1H": "1h", "4H": "4h", "1D": "1d", "1W": "1w" };
const yahooIntervals: Record<string, string> = { "1m": "1m", "5m": "5m", "15m": "15m", "30m": "30m", "1H": "1h", "4H": "1h", "1D": "1d", "1W": "1wk" };
const yahooRanges: Record<string, string> = { "1m": "1d", "5m": "5d", "15m": "1mo", "30m": "1mo", "1H": "3mo", "4H": "6mo", "1D": "2y", "1W": "5y" };
function cryptoProvider(symbol: string) { return `${symbol.replace(/USD$/, "")}USDT`; }
async function yahooCandles(symbol: string, interval: string, range: string) { const response = await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=${range}&interval=${interval}`, { headers: { accept: "application/json" }, cache: "no-store", signal: AbortSignal.timeout(6000) }); if (!response.ok) throw new Error("外部 K 线行情源暂时不可用"); const payload = await response.json() as { chart?: { result?: Array<{ timestamp?: number[]; indicators?: { quote?: Array<{ open?: Array<number | null>; high?: Array<number | null>; low?: Array<number | null>; close?: Array<number | null>; volume?: Array<number | null> }> } }> } }; const result = payload.chart?.result?.[0]; const timestamp = result?.timestamp || []; const row = result?.indicators?.quote?.[0]; return timestamp.map((time, index) => ({ time: time * 1000, open: Number(row?.open?.[index] || 0), high: Number(row?.high?.[index] || 0), low: Number(row?.low?.[index] || 0), close: Number(row?.close?.[index] || 0), volume: Number(row?.volume?.[index] || 0) })).filter(candle => candle.open > 0 && candle.high > 0 && candle.low > 0 && candle.close > 0); }
export async function GET(request: Request) { const url = new URL(request.url); const symbol = (url.searchParams.get("symbol") || "BTCUSD").toUpperCase().replace("/", ""); const category = (url.searchParams.get("category") || "crypto") as Category; const interval = url.searchParams.get("interval") || "15m"; try { let candles: Candle[]; let source = "Yahoo Finance public chart"; if (category === "crypto") { const { data: rows, base } = await fetchPublicMarketJson<Array<[number, string, string, string, string, string]>>(`/api/v3/klines?symbol=${cryptoProvider(symbol)}&interval=${binanceIntervals[interval] || "15m"}&limit=160`, 6000); candles = rows.map(row => ({ time: row[0], open: Number(row[1]), high: Number(row[2]), low: Number(row[3]), close: Number(row[4]), volume: Number(row[5]) })); source = publicMarketProviderName(base); } else candles = await yahooCandles(yahooSymbols[symbol] || symbol, yahooIntervals[interval] || "15m", yahooRanges[interval] || "1mo"); return Response.json({ symbol, interval, live: candles.length > 0, source, updatedAt: new Date().toISOString(), candles }, { headers: { "cache-control": "no-store" } }); } catch (error) { return Response.json({ symbol, interval, live: false, source: "unavailable", updatedAt: new Date().toISOString(), candles: [], error: error instanceof Error ? error.message : "K 线源暂时不可用" }, { status: 503, headers: { "cache-control": "no-store" } }); } }
