import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { approvalRequests, auditLogs, authTokens, notificationDeliveries, organizations, users } from "@/db/schema";
import { hashPassword, normalizeEmail, randomToken, sha256, validEmail } from "@/lib/auth";
import { childRole } from "@/lib/permissions";
import { requireUser, responseError } from "@/lib/session";

const creators = ["hq_admin","branch_admin","manager","supervisor"] as const;
export async function GET(request:Request){try{const user=await requireUser(request,[...creators]);const target=childRole[user.role];if(!target)return Response.json({members:[]});const db=getDb();let rows;if(user.role==="hq_admin")rows=await db.select({id:users.id,email:users.email,role:users.role,status:users.status,organizationId:users.organizationId,createdAt:users.createdAt}).from(users).where(eq(users.role,"branch_admin")).orderBy(desc(users.createdAt)).limit(200);else rows=await db.select({id:users.id,email:users.email,role:users.role,status:users.status,organizationId:users.organizationId,createdAt:users.createdAt}).from(users).where(and(eq(users.role,target as typeof users.$inferSelect.role),eq(users.organizationId,user.organizationId!))).orderBy(desc(users.createdAt)).limit(200);return Response.json({members:rows,nextRole:target});}catch(e){return responseError(e)}}

export async function POST(request:Request){try{const actor=await requireUser(request,[...creators]);const body=await request.json() as {email?:string,name?:string};const email=normalizeEmail(body.email??"");if(!validEmail(email))return Response.json({error:"请输入有效邮箱"},{status:400});const role=childRole[actor.role] as typeof users.$inferInsert.role|undefined;if(!role||role==="customer")return Response.json({error:"该角色不能创建内部成员"},{status:403});const db=getDb();if((await db.select({id:users.id}).from(users).where(eq(users.email,email)).limit(1))[0])return Response.json({error:"邮箱已存在"},{status:409});let organizationId=actor.organizationId;const userId=crypto.randomUUID();const now=new Date().toISOString();if(role==="branch_admin"){organizationId=crypto.randomUUID();await db.insert(organizations).values({id:organizationId,type:"branch",name:body.name?.trim()||email.split("@")[0]});}const temporaryPassword=randomToken(8);const verifyToken=randomToken();await db.batch([db.insert(users).values({id:userId,email,passwordHash:await hashPassword(temporaryPassword),role,organizationId,reportsToUserId:actor.id,status:"pending"}),db.insert(authTokens).values({id:crypto.randomUUID(),userId,tokenHash:await sha256(verifyToken),purpose:"verify_email",expiresAt:new Date(Date.now()+48*3600_000).toISOString()}),db.insert(notificationDeliveries).values({id:crypto.randomUUID(),userId,channel:"email",category:"login_security",templateKey:"internal_account_invite",payloadJson:JSON.stringify({verifyToken,temporaryPassword,role}),scheduledAt:now}),db.insert(auditLogs).values({id:crypto.randomUUID(),actorUserId:actor.id,action:"organization.member_created",subjectType:"user",subjectId:userId,afterJson:JSON.stringify({email,role,organizationId})})]);return Response.json({member:{id:userId,email,role,status:"pending"},message:"成员已创建，激活邮件进入发送队列"},{status:201});}catch(e){return responseError(e)}}
export async function PATCH(request:Request){try{const actor=await requireUser(request,["branch_admin"]),body=await request.json()as{memberId?:string,newReportsToUserId?:string,reason?:string};if(!body.memberId||!body.newReportsToUserId||!body.reason?.trim())return Response.json({error:"成员、新上级和调整原因均为必填"},{status:400});const db=getDb(),member=(await db.select().from(users).where(eq(users.id,body.memberId)).limit(1))[0],leader=(await db.select().from(users).where(eq(users.id,body.newReportsToUserId)).limit(1))[0];if(!member||!leader||member.organizationId!==actor.organizationId||leader.organizationId!==actor.organizationId)return Response.json({error:"成员或上级不属于当前分公司"},{status:403});const allowed=(member.role==="manager"&&leader.role==="branch_admin")||(member.role==="supervisor"&&leader.role==="manager")||(member.role==="employee"&&leader.role==="supervisor");if(!allowed)return Response.json({error:"上下级角色关系不符合组织层级"},{status:400});const id=crypto.randomUUID();await db.insert(approvalRequests).values({id,type:"reporting_line_change",branchId:actor.organizationId,subjectType:"user",subjectId:member.id,payloadJson:JSON.stringify({previousReportsToUserId:member.reportsToUserId,newReportsToUserId:leader.id,reason:body.reason.trim()}),requestedBy:actor.id});return Response.json({approvalId:id,status:"pending",message:"上下级调整已提交双人审批"},{status:201})}catch(e){return responseError(e)}}
